import "./globals.css";
import type { Metadata } from "next";
// import * as google from "next/font/google";
import Navbar from "./components/Navbar";
import { draftMode } from "next/headers";
import cmsdata from "../../lib/datocms";
import { FONT_QUERY } from "../../query/FontQuery";
// import { NextFont } from "next/dist/compiled/@next/font";

// const inter = Inter({ subsets: ['latin'] })
import * as google from "next/font/google/index";
import { fontSelector } from "../../fonts/font";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const { isEnabled } = draftMode();
  const fontStyleValue: FontQueryType = await cmsdata({
    query: FONT_QUERY,
    includeDrafts: isEnabled,
  });
  // const font = await import("next/font/google/index")
  const fontValue = fontStyleValue.goggleFont.font || 'inter';
  // const fontStyle = font["Inter"];
  // const fontStyleApply = font({
  //   subsets: ["latin"],
  // });

  // console.log(fontStyleApply)
  

  return (
    <html lang="en">
      <body className={fontSelector[fontValue].className}>
        <Navbar draft={draftMode().isEnabled} />
        {children}
      </body>
    </html>
  );
}
